### ISSUE TITLE
AttributeError: partially initialized module 'aedat' has no attribute 'Decoder' (most likely due to a circular import)

### ISSUE THREAD

**Issue by Zizzzzzzz** [neuromorphicsystems/aedat#11]
Hi, when I try to run the example, this error occurs.
Could you please help me?
`Traceback (most recent call last):
  File "aedat.py", line 1, in <module>
    import aedat
  File "/root/data1/code/ICCV2021_Event_Frame_Tracking-main/aedat.py", line 3, in <module>
    decoder = aedat.Decoder("/root/data1/dataset/FE108/img_ext/airplane/events.aedat4")
AttributeError: partially initialized module 'aedat' has no attribute 'Decoder' (most likely due to a circular import)`

**Comment by aMarcireau** [comment]
Hi, 

Could you share your code so that I may replicate the error on my machine?

**Comment by Zizzzzzzz** [comment]
> `import aedat
> # from aedat import Decoder
> decoder = aedat.Decoder("/root/data1/dataset/FE108/img_ext/airplane/events.aedat4")
> print(decoder.id_to_stream())
> 
> for packet in decoder:
>     print(packet["stream_id"], end=": ")
>     if "events" in packet:
>         print("{} polarity events".format(len(packet["events"])))
>     elif "frame" in packet:
>         print("{} x {} frame".format(packet["frame"]["width"], packet["frame"]["height"]))
>     elif "imus" in packet:
>         print("{} IMU samples".format(len(packet["imus"])))
>     elif "triggers" in packet:
>         print("{} trigger events".format(len(packet["triggers"])))`

**Comment by aMarcireau** [comment]
By any chance, did you name your test script "aedat.py"? This can confuse Python and cause the error you observed. If it is the case, renaming your script to anything else should fix the problem.

**Comment by Zizzzzzzz** [comment]
Yes! It is the case! Thank you very much!
