### ISSUE TITLE
Using 'p' as an alias for 'on' event attribute

### ISSUE THREAD

**Issue by biphasic** [neuromorphicsystems/aedat#16]
Similarly as in https://github.com/neuromorphicsystems/event_stream/issues/2, I would like to know if it's possible to use the [field title](https://numpy.org/doc/stable/user/basics.rec.html#field-titles) 'p' as an alias for the event attribute 'on', to make downstream workflows with Tonic easier. Thank you!
```
events = events_from_aedat.view(dtype=events.dtype.descr[:3] + [(('on', 'p'), '?')])
assert all(events['p'] == events['on'])
```

**Comment by aMarcireau** [comment]
@biphasic Implemented in 2.1.0.
