### ISSUE TITLE
RuntimeError: the packet does not have a size prefix

### ISSUE THREAD

**Issue by zhang-pengyu** [neuromorphicsystems/aedat#4]
Thanks for your inspiring toolkit for extracting the aedat4 file. When I decode the data from DAVIS346 with the latest DV platform,  an exception has occurred: "RuntimeError the packet does not have a size prefix". I wonder how to counter this error. BTW, I found that this package does not support Macbook M1 with ARM arch. Will you update a new version for supporting this? Thanks in advance.

**Comment by aMarcireau** [comment]
Thank you for your interest! Concerning the DAVIS346 recording, could you send it to me via email or a cloud link? I did not run into this issue with my recordings and would need yours to investigate the issue.

Since I do not have an ARM mac, I cannot pre-compile the package for this architecture and upload it on PyPI (pip). Have you tried building AEDAT from source (https://github.com/neuromorphicsystems/aedat#install-from-source)? Let me know if you try and run into issues.

**Comment by zhang-pengyu** [comment]
And, I have installed it from source following the document in PyPI. When executing 'cargo build --release', error occurs.

error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-arch" "arm64" "-L" "/Users/zpy/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib" "/Users/zpy/aedat/target/release/deps/aedat.aedat.8z8sjkra-cgu.2.rcgu.o" "-o" "/Users/zpy/aedat/target/release/deps/libaedat.dylib" "-Wl,-exported_symbols_list,/var/folders/kd/svmw08f551sdcjkc0qqqrvqm0000gn/T/rustcWih2yZ/list" "-Wl,-dead_strip" "-dynamiclib" "-Wl,-dylib" "-nodefaultlibs" "-L" "/Users/zpy/aedat/target/release/deps" "-L" "/Users/zpy/aedat/target/release/build/lz4-sys-27988139e4244dfa/out" "-L" "/Users/zpy/aedat/target/release/build/zstd-sys-7053643a88265347/out" "-L" "/Users/zpy/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib" "/var/folders/kd/svmw08f551sdcjkc0qqqrvqm0000gn/T/rustcWih2yZ/libzstd_sys-89fd2ab83927db9e.rlib" "/var/folders/kd/svmw08f551sdcjkc0qqqrvqm0000gn/T/rustcWih2yZ/liblz4_sys-7b1b0fdc5c36e7ad.rlib" "/Users/zpy/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcompiler_builtins-9eb7dc999785b765.rlib" "-lSystem" "-lresolv" "-lc" "-lm"

The error  'ld: symbol(s) not found for architecture arm64'  may stem from some dependencies are not for ARM architecture.
Could you give me some guidance on debugging it?

**Comment by aMarcireau** [comment]
The "RuntimeError" issue actually came from a regression I introduced after the last update. The new version (1.2.0) corrects it.

ARM macs are lacking native Rust support for the moment (https://github.com/rust-lang/rust/issues/73908). Here are a few workarounds (I couldn't try them so I don't know whether they actually work):
- Run a Rosetta terminal (https://stackoverflow.com/questions/64882584/how-to-run-the-homebrew-installer-under-rosetta-2-on-m1-macbook) and install Python and pip from there (or alternatively compile the native version from this terminal)
- Use DV, the official AEDAT library from Inivation (https://gitlab.com/inivation/dv/dv-python)
- Use the unofficial C++ decoder https://github.com/norse/aedat

**Comment by zhang-pengyu** [comment]
Thanks a lot. The newer version works. And the official aedat library from Inivation can work on my PC with ARM arch :)
